### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Hyrules**
3.0.4331.0

### CODE REVIEW

**Comment by banksio** [comment]
Just rebuilt the website and fixed a few links on the readme (.NET 4.5.2 etc.). Just thought I'd let you know that the link on the repo homepage still has WinHue3 on the end.
image

**Comment by Hyrules** [comment]
Thanks ! I was wondering why the site was not working. I fixed it.

**Comment by Hyrules** [comment]
Some images needs to be recaptured on the site the group creator for example. Strike that all screen captures need to be redone.

**Comment by banksio** [comment]
Yeah I was literally just thinking that lol, I'll get round to them soon - probably this weekend. Or if you want to do them and send them to me I can add them - need to add stuff for the new creators like floorplan too.

**Comment by Hyrules** [comment]
Here you go :
facturePR
facturePR_M
Mainform
groupcreator
schedulecreator
rulecreator
bridgedetection

**Comment by banksio** [comment]
@Hyrules Nice thanks, I'll update the website tomorrow.

**Comment by Hyrules** [comment]
I have been thinking about lights and I have decided to remove the unreachable state as an image and simply implement an visual cue in WinHue like a greyed out light. This will make the light status a simple binary operation on (true) or off (false). Might take less memory as well. Also I've been thinking of completely reworking the philips hue api part. I want to remove the idea of a selected bridge. If every object is aware of it's path it could work by itself and WinHue could simply list all Objects in a window instead of having to select different bridge. This will need a major overhaul of the system. I have also added an image for the Entertainment group as a tv. I need to fix the light toggling part.

**Comment by banksio** [comment]
@Hyrules That sounds good, I was going to look into manipulating the bulb colours in code, so they can show the right colours that they are currently on. Could possibly achieve greying out the bulb by this method and remove the need for another image. Either way is good! Haven't got round to updating the website yet, will do that very soon...

The multiple bridges idea sounds like a fair bit of work. Personally I only have one bridge so I couldn't help test but I think it sounds like a good idea.

**Comment by Hyrules** [comment]
What i'll do is create a new branch from the dev branch and work on that one. it will still leave the current api untouch in case of any issues.

**Comment by banksio** [comment]
> I'll update the website tomorrow.

@Hyrules Oops, this is long overdue, sorry about that.

I've been updating the website this evening and got a test page. Basically I was thinking to split the website up because there are a lot of new features in WinHue, so we could have the main features on the homepage and then a more detailed features page. I've added a proper navigation bar so we could add more pages later (maybe a news/blog page to explain the changelogs? anyway that's not for the moment).

Let me know what you think (the homepage isn't updated yet just the features page). https://banksio.github.io/WinHue/

**Comment by Hyrules** [comment]
Some images seems to be missing in the main page. I would pull the menu to the left as well. This would seem more natural. Other than that the site seems good to me.

**Comment by banksio** [comment]
@Hyrules Yeah that's intended at the mo, didn't finish the main page yet. I'll shift the menu over to the left.

**Comment by banksio** [comment]
I hope to have this done soon, I have been quite busy sorry about that. Please could you send me the screenshots for the sensor creator, bridge settings and user management? (If you want to have screenshots of these, if not I'll just write text about them)

**Comment by Hyrules** [comment]
image
image
image

Here you go. Don't need to hurry. I havn't worked on WinHue for a while. I been taking a little break. Don't know when I'll start again.

**Comment by banksio** [comment]
All good, perfect thanks. I will let you know when it's done! 😃

**Comment by banksio** [comment]
Finally updated the website, I've left the other pages I'm planning on adding to later. I have a bad habit of making a small task bigger, should've just updated the screenshots and uploaded that, then worked on the other changes later. But it's done now. ☺️

**Pull request merged**
